"""Regenerate responsive WebP assets and metadata; requires Pillow."""
import json
from pathlib import Path
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
output = ROOT / 'public/info_images/optimised'
output.mkdir(exist_ok=True)
manifest = {}
for source in sorted((ROOT / 'public/info_images').iterdir()):
    if source.suffix.lower() not in {'.jpg', '.jpeg', '.png'}:
        continue
    with Image.open(source) as original:
        image = ImageOps.exif_transpose(original).convert('RGB')
        widths = sorted({min(width, image.width) for width in (480, 960, 1440)})
        variants = []
        for width in widths:
            height = round(image.height * width / image.width)
            name = f'{source.stem}-{width}.webp'
            image.resize((width, height), Image.Resampling.LANCZOS).save(output / name, 'WEBP', quality=80, method=6)
            variants.append({'url': f'./info_images/optimised/{name}', 'width': width})
        manifest[f'./info_images/{source.name}'] = {
            'width': image.width, 'height': image.height, 'variants': variants,
        }
with Image.open(ROOT / 'public/images/sun.jpg') as image:
    image.resize((1024, 512), Image.Resampling.LANCZOS).save(ROOT / 'public/images/sun-1024.webp', 'WEBP', quality=82, method=6)
(ROOT / 'src/generated/image-manifest.js').write_text(
    '// Generated by scripts/optimise-images.py\nexport const imageManifest = ' + json.dumps(manifest, indent=2) + ';\n'
)
